### ISSUE TITLE
template

### ISSUE THREAD

**Issue by tuanvq95** [tieuquyngok1995/ToolSupportUchida#47]
1/		mType khác ""															
																	
		1.1/ 		mMsgDesc khác ""													
																	
					message.title = "エラー情報"												
					mType = 48 + mType												
		1.2/ 		mMsgDesc = ""													
																	
					message.title = "通知"												
																	
		1.3/ 		mMsgCode khác ""													
																	
					message.title = "エラー情報"												
																	
		1.3/		mQuestion khác ""													
																	
					message.title = "確認"												
																	
		1.4/		Nếu phần tử đầu tiên bên phải của chuỗi đầu tiên được cắt từ mMsgDesc bằng ":" , độ lớn chuỗi đầu tiên là 9													
																	
					message.title = "確認"												
																	
																	
2/		mType = ""															
																	
		mIcon = phần tử thứ 1 của mQuestion cắt bằng ","															
		mButtonType = phần tử thứ 2 của mQuestion cắt bằng ","															
																	
		2.1/ 		 mIcon = "C"													
						mType = 16											
						message.title =  "警告"											
				mIcon =  "Q"													
						mType = 32											
						message.title =  "問い合わせ"											
				 mIcon = "E"													
						mType = 48											
						message.title =  "注意"											
				 mIcon = "I"													
						mType = 64											
						message.title =  "情報"											
																	
		2.2/ 		mButtonType = 0													
						mType = mType + 0											
				mButtonType = 1													
						mType = mType + 1											
				mButtonType = 2													
						mType = mType + 2											
				mButtonType = 3													
						mType = mType + 3 + 256											
				mButtonType = 4													
						mType = mType + 4 + 256											
				mButtonType = 5													
						mType = mType + 5 + 256

**Comment by tieuquyngok1995** [comment]
Function I_MSGDISP(mMsgCode, mMsgDesc, mMsgDescHojyo, mQuestion, mType)

**Comment by tieuquyngok1995** [comment]
// 確認メッセージ(エラー区分＝"M"など)の場合
Utils.createMessage(
  response.errMessage,
  response.errMessageHosoku
)
// エラーメッセージの場合
Utils.createErrorMessage(
  response.errMessage,
  response.errMessageHosoku,
  response.errMessageNo
)

**Comment by tieuquyngok1995** [comment]
// 確認メッセージ(エラー区分＝"M"など)の場合
Utils.createMessage(
  response.errMessage,
  null
)
// エラーメッセージの場合
Utils.createErrorMessage(
  response.errMessage,
  null,
  response.errMessageNo
)

**Comment by tieuquyngok1995** [comment]
fa fa-xs fa-sm
